### PR TITLE
Update parameter for Jest 27

### PR DESCRIPTION
**Pull request by karlhorky**
Ref: https://jestjs.io/docs/next/code-transformation#writing-custom-transformers

Original issue: https://github.com/ikatyang/dts-jest/issues/404

### CODE REVIEW

**Comment by karlhorky** [comment]
Hm, the Node 6 Travis test fails with something unrelated:

```
1.15s$ yarn global add codecov
yarn global v1.22.4
[1/4] Resolving packages...
inimatch@^3.0.4[2/4] Fetching packages...
error teeny-request@7.0.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "6.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
The command "yarn global add codecov" failed and exited with 1 during .
```

**Comment by karlhorky** [comment]
Ok, fixed the Node Stable test at least:

Screen Shot 2021-05-30 at 12 37 15

**Review by ikatyang — APPROVED** [review]

**Comment by ikatyang** [comment]
Thanks!

**Comment by karlhorky** [comment]
Thanks! I guess this was released in `24.0.0` - I'll give it a try!

**Comment by karlhorky** [comment]
Yep, looks like `24.0.0` working without my `patch-package` patch, thanks for the fast response!

**Pull request merged**
